// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TpI7kheWrXRMmgqZMCIHYTSKzBofOjY',
    appId: '1:882705725137:web:ae35054c606c1e370237f0',
    messagingSenderId: '882705725137',
    projectId: 'donezy-eee27',
    authDomain: 'donezy-eee27.firebaseapp.com',
    storageBucket: 'donezy-eee27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMB3gW93hh_J2788E2DI_PgEvVvneMwiM',
    appId: '1:882705725137:android:490feb5acc9c4d640237f0',
    messagingSenderId: '882705725137',
    projectId: 'donezy-eee27',
    storageBucket: 'donezy-eee27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxRJOcdh8oUzrx34FZA0c1sn9P1WOgk8',
    appId: '1:882705725137:ios:cf061a93deade5090237f0',
    messagingSenderId: '882705725137',
    projectId: 'donezy-eee27',
    storageBucket: 'donezy-eee27.firebasestorage.app',
    iosBundleId: 'com.example.donezyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxRJOcdh8oUzrx34FZA0c1sn9P1WOgk8',
    appId: '1:882705725137:ios:cf061a93deade5090237f0',
    messagingSenderId: '882705725137',
    projectId: 'donezy-eee27',
    storageBucket: 'donezy-eee27.firebasestorage.app',
    iosBundleId: 'com.example.donezyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1TpI7kheWrXRMmgqZMCIHYTSKzBofOjY',
    appId: '1:882705725137:web:e62eecf83cb045cc0237f0',
    messagingSenderId: '882705725137',
    projectId: 'donezy-eee27',
    authDomain: 'donezy-eee27.firebaseapp.com',
    storageBucket: 'donezy-eee27.firebasestorage.app',
  );

}